spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: admin
    h2:
      console:
        enabled: true
        path: /h2-console
        settings:
          web-allow-others: true
conf:
  base-url: ${BASE_URL}
  token-tnk-read: ${TOKEN_TNK_READ}